export const TYPE = {
  display: {
    fontFamily: "'Outfit', 'Helvetica Neue', sans-serif",
    fontSize: "clamp(56px, 8vw, 96px)",
    fontWeight: 300,
    lineHeight: 1.0,
    letterSpacing: "-0.04em",
  },
  h1: {
    fontFamily: "'Outfit', 'Helvetica Neue', sans-serif",
    fontSize: "clamp(40px, 6vw, 72px)",
    fontWeight: 300,
    lineHeight: 1.05,
    letterSpacing: "-0.03em",
  },
  h2: {
    fontFamily: "'Outfit', 'Helvetica Neue', sans-serif",
    fontSize: "clamp(28px, 4vw, 52px)",
    fontWeight: 400,
    lineHeight: 1.1,
    letterSpacing: "-0.025em",
  },
  h3: {
    fontFamily: "'Outfit', 'Helvetica Neue', sans-serif",
    fontSize: "clamp(20px, 2.5vw, 28px)",
    fontWeight: 500,
    lineHeight: 1.25,
    letterSpacing: "-0.015em",
  },
  bodyLg: {
    fontFamily: "'Outfit', 'Helvetica Neue', sans-serif",
    fontSize: "clamp(17px, 2vw, 20px)",
    fontWeight: 300,
    lineHeight: 1.65,
    letterSpacing: "0em",
  },
  body: {
    fontFamily: "'Outfit', 'Helvetica Neue', sans-serif",
    fontSize: "16px",
    fontWeight: 400,
    lineHeight: 1.65,
    letterSpacing: "0em",
  },
  bodySm: {
    fontFamily: "'Outfit', 'Helvetica Neue', sans-serif",
    fontSize: "14px",
    fontWeight: 400,
    lineHeight: 1.6,
    letterSpacing: "0em",
  },
  label: {
    fontFamily: "'Outfit', 'Helvetica Neue', sans-serif",
    fontSize: "11px",
    fontWeight: 500,
    lineHeight: 1.4,
    letterSpacing: "0.1em",
    textTransform: "uppercase" as const,
  },
  meta: {
    fontFamily: "'Outfit', 'Helvetica Neue', sans-serif",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: 1.4,
    letterSpacing: "0.08em",
    textTransform: "uppercase" as const,
  },
  nav: {
    fontFamily: "'Outfit', 'Helvetica Neue', sans-serif",
    fontSize: "15px",
    fontWeight: 400,
    lineHeight: 1,
    letterSpacing: "0em",
  },
  button: {
    fontFamily: "'Outfit', 'Helvetica Neue', sans-serif",
    fontSize: "15px",
    fontWeight: 500,
    lineHeight: 1,
    letterSpacing: "0em",
  },
} as const;

export const SPACING = {
  sectionPy: { desktop: "96px", mobile: "64px" },
  sectionPx: "24px",
  maxWidth: "1200px",
  headingToSub: "20px",
  subToCta: "40px",
  labelToH2: "16px",
  cardPadding: "28px",
  cardGap: "20px",
} as const;
