export const TYPE = {
  display: {
    fontFamily: "'Syne', sans-serif",
    fontSize: "clamp(2.5rem, 5vw, 4rem)",
    fontWeight: 800,
    lineHeight: 1.0,
    letterSpacing: "-0.02em",
  },
  h1: {
    fontFamily: "'Syne', sans-serif",
    fontSize: "clamp(2.5rem, 5vw, 4rem)",
    fontWeight: 800,
    lineHeight: 1.05,
    letterSpacing: "-0.02em",
  },
  h2: {
    fontFamily: "'Syne', sans-serif",
    fontSize: "clamp(2rem, 3.5vw, 2.75rem)",
    fontWeight: 700,
    lineHeight: 1.1,
    letterSpacing: "-0.02em",
  },
  h3: {
    fontFamily: "'Syne', sans-serif",
    fontSize: "clamp(1.5rem, 2.5vw, 2rem)",
    fontWeight: 600,
    lineHeight: 1.25,
    letterSpacing: "-0.015em",
  },
  bodyLg: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: "clamp(17px, 2vw, 20px)",
    fontWeight: 300,
    lineHeight: 1.65,
    letterSpacing: "0em",
  },
  body: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: "16px",
    fontWeight: 400,
    lineHeight: 1.65,
    letterSpacing: "0em",
  },
  bodySm: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: "14px",
    fontWeight: 400,
    lineHeight: 1.6,
    letterSpacing: "0em",
  },
  label: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: "11px",
    fontWeight: 500,
    lineHeight: 1.4,
    letterSpacing: "0.1em",
    textTransform: "uppercase" as const,
  },
  meta: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: 1.4,
    letterSpacing: "0.08em",
    textTransform: "uppercase" as const,
  },
  nav: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: "15px",
    fontWeight: 400,
    lineHeight: 1,
    letterSpacing: "0em",
  },
  button: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: "15px",
    fontWeight: 500,
    lineHeight: 1,
    letterSpacing: "0em",
  },
} as const;

export const SPACING = {
  sectionPy: { desktop: "96px", mobile: "64px" },
  sectionPx: "24px",
  maxWidth: "1200px",
  headingToSub: "20px",
  subToCta: "40px",
  labelToH2: "16px",
  cardPadding: "28px",
  cardGap: "20px",
} as const;
